task_management/task_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("activite_log/", include("activite_log.urls")),
    path("tasks/", include("tasks.urls")),
    path("notifications/", include("notifications.urls")),
    path("users/", include("users.urls")),
    
    
]

task_management/tasks/urls.py
from django.urls import path
from .views import TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView

urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('create/', TaskCreateView.as_view(), name='task_create'),
    path('update/<int:pk>/', TaskUpdateView.as_view(), name='task_update'),
    path('delete/<int:pk>/', TaskDeleteView.as_view(), name='task_delete'),
]

task_management/notifications/models.py
"""
    Modelo que representa una notificación relacionada con una tarea.

    Atributos:
    task (ForeignKey): Relación con el modelo Task; indica a qué tarea está asociada la notificación.
    message (CharField): Mensaje de la notificación, máximo 255 caracteres.
    created_at (DateTimeField): Fecha y hora en que se creó la notificación, se establece automáticamente.

    Métodos:
    __str__(): Devuelve el mensaje de la notificación.
"""

from django.db import models
from django.contrib.auth.models import User

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message[:50]

task_management/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Tareas{% endblock %}</title>
    {% comment %} <link rel="stylesheet" href="{% static 'css/styles.css' %}"> {% endcomment %}
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'activite_log_list' %}">Actividades</a></li>
                <li><a href="{% url 'task_list' %}">Tareas</a></li>
                <li><a href="{% url 'notification_list' %}">Notificaciones</a></li>
                <li><a href="{% url 'user_profile' %}">Usuario</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Tareas</p>
    </footer>
</body>
</html>